name = "nexus-git-agent"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "049ff5e84ecf636b53b162cbb580aae6"

[[kv_namespaces]]
binding = "NEXUS_KV"
id = "c46ecbe2f4d640ddb0162223babe82e9"
